# Generated by Django 2.2 on 2019-05-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mydocs/', verbose_name='Document')),
                ('fname', models.CharField(max_length=70)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('category', models.CharField(choices=[('Statitics', 'Statitics'), ('Probabilty', 'Probabilty'), ('Algebra', 'Relational Algebra'), ('Geometry', 'Geometry')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('img', models.ImageField(default='download.jpeg', upload_to='gallery')),
                ('status', models.BooleanField(default=True, verbose_name='Approve')),
                ('g_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=70)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=100)),
                ('district', models.CharField(choices=[('alp', 'Alappuzha'), ('ekm', 'Ernakulam'), ('idk', 'Idukki'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('kol', 'Kollam'), ('ktm', 'Kottayam'), ('koz', 'Kozhikode'), ('mpm', 'Malappuram'), ('pkd', 'Palakkad'), ('ptm', 'Pathanamthitta'), ('tvm', 'Thiruvananthapuram'), ('tcr', 'Thrissur'), ('wnd', 'Wayanad')], max_length=40)),
                ('position', models.CharField(choices=[('Director', 'Director'), ('Chairman', 'Chairman'), ('Associate Director', 'Associate Director'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Member', 'Member')], max_length=30)),
                ('invigilation', models.CharField(max_length=250, verbose_name='Invigilation ')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('organisation', models.CharField(max_length=250, verbose_name='Organization / Institution')),
                ('department', models.CharField(max_length=250, verbose_name='Department ')),
                ('address', models.TextField()),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('alp', 'Alappuzha'), ('ekm', 'Ernakulam'), ('idk', 'Idukki'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('kol', 'Kollam'), ('ktm', 'Kottayam'), ('koz', 'Kozhikode'), ('mpm', 'Malappuram'), ('pkd', 'Palakkad'), ('ptm', 'Pathanamthitta'), ('tvm', 'Thiruvananthapuram'), ('tcr', 'Thrissur'), ('wnd', 'Wayanad')], max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('organisation', models.CharField(max_length=250, verbose_name='Organization / Institution')),
                ('address', models.TextField()),
                ('joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('venue', models.CharField(max_length=70)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('district', models.CharField(choices=[('alp', 'Alappuzha'), ('ekm', 'Ernakulam'), ('idk', 'Idukki'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('kol', 'Kollam'), ('ktm', 'Kottayam'), ('koz', 'Kozhikode'), ('mpm', 'Malappuram'), ('pkd', 'Palakkad'), ('ptm', 'Pathanamthitta'), ('tvm', 'Thiruvananthapuram'), ('tcr', 'Thrissur'), ('wnd', 'Wayanad')], max_length=40)),
                ('sdate', models.DateTimeField()),
                ('info', models.TextField()),
                ('fdate', models.DateField()),
                ('wtype', models.CharField(choices=[('Workshops', 'Workshops'), ('Conferences', 'Conferences'), ('Seminars', 'Seminars')], max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
